# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Let the linting begin
  #       shell: pwsh
  #       run: |
  #         write-host "Linting"
  #         write-host "Success!" -ForegroundColor Green

  # # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   name: Build

  #   # wait till lintings done
  #   needs: lint

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3

  #     - name: Building
  #       shell: pwsh
  #       run: |
  #         write-host "Building stuff"
  #         write-host "Success!" -ForegroundColor Green
  
  tests:
    name: Quality Assurance
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Functional tests
        shell: pwsh
        run: |
          write-host "Running functional tests"
          write-host "Success!" -ForegroundColor Green
      
      - name: Integration tests
        shell: pwsh
        run: |
          write-host "Running integration tests"
          write-host "Success!" -ForegroundColor Green

      - name: Execute script
        # shell: pwsh
        run: |
          pwsh $GITHUB_WORKSPACE/cicd/Hello-World.ps1
